"""Packs a checkpoint into the flat blob the C++ bot memory-maps at start-up.

bfloat16 rather than float16: widening is `u32 = u16 << 16` with no exponent
rebiasing, which matters because the bot pays CPU points for every one of the
~1.9M conversions it does on its first turn. The teacher was trained under
bf16 autocast anyway, so this costs no accuracy it had not already accepted.

Layout is a header of int32s then every tensor back to back, in the order the
bot reads them. Conv kernels are stored (Cout, Cin*9) to match the im2col
gemm. Linear weights are stored transposed, (in, out), so the bot computes
each layer as a sum of scaled rows -- an axpy per input, contiguous over the
outputs -- which vectorises. The (out, in) layout makes each output a dot
product, a serial float reduction that -O2 cannot vectorise without
reassociating, and measured ~15 points per MAC against ~3.3.

The judge runs the bot as wasm with no filesystem, so a data file beside the
sources is invisible to it (every C++ submission up to v4 silently fell back
to its heuristic for this reason). The weights are therefore compiled in:
`--header` writes mybot/weights_data.hpp, which holds them as two string
literals of raw bytes, the high and the low byte of every bf16 value.

  * Raw bytes, not base64: the bytes land in the wasm data segment as they
    are, so the first turn only widens them. Decoding base64 at start-up was
    metered at ~250M points, over the 100M turn limit.
  * Printable bytes are written as themselves and the rest as three-digit
    octal escapes, which cannot run on into a following digit the way hex
    escapes do.
  * Split into planes, the high bytes (sign and exponent) repeat a lot, so
    the zip (~2.7MB) stays well under the 4MB limit; a string literal is also
    cheap for the judge's compiler where a 1.5M-element array is not.

The header also carries the shape and a checksum. The literal's length is a
compile-time check, and the bot verifies shape and checksum before trusting
the weights.

    python -m train.export_cpp --ckpt runs/v2/snapshots/turns_X.pt
"""

from __future__ import annotations

import argparse
import pathlib
import struct
import time

import numpy as np
import torch

ROOT = pathlib.Path(__file__).resolve().parents[2]  # repo root

MAGIC = 0x42434E32          # "BCN2": linear weights stored transposed


def bf16(x: np.ndarray) -> np.ndarray:
    """Round-to-nearest-even truncation of float32 to its top 16 bits."""
    u = x.astype(np.float32).view(np.uint32)
    rounded = (u + 0x7FFF + ((u >> 16) & 1)) >> 16
    return rounded.astype(np.uint16)


def checksum(u: np.ndarray) -> int:
    """FNV-1a over the bf16 values, as net::checksum computes it."""
    h = 2166136261
    for v in u.tolist():
        h = ((h ^ v) * 16777619) & 0xFFFFFFFF
    return h


def write_header(dest: pathlib.Path, u: np.ndarray, width: int, blocks: int, hidden: int,
                 head: int, source: str) -> None:
    safe = [chr(c) if 32 <= c < 127 and chr(c) not in '"\\?' else "\\%03o" % c
            for c in range(256)]

    def literal(plane: np.ndarray) -> str:
        step = 2048
        data = plane.astype(np.uint8).tobytes()
        return "\n".join('    "' + "".join(safe[c] for c in data[i:i + step]) + '"'
                         for i in range(0, len(data), step))

    hi, lo = literal(u >> 8), literal(u & 0xFF)

    dest.write_text(
        "// GENERATED by bcsim/train/export_cpp.py --header. Do not edit.\n"
        f"// source: {source}\n"
        f"// written: {time.strftime('%Y-%m-%d %H:%M:%S')}\n"
        "#pragma once\n\n#include <cstdint>\n\nnamespace embedded {\n\n"
        f"constexpr int WIDTH = {width};\n"
        f"constexpr int BLOCKS = {blocks};\n"
        f"constexpr int HIDDEN = {hidden};\n"
        f"constexpr int HEAD = {head};\n"
        f"constexpr std::uint32_t COUNT = {u.size}u;       // bf16 values\n"
        f"constexpr std::uint32_t CHECKSUM = {checksum(u)}u;   // FNV-1a over them\n"
        f'constexpr char const SOURCE[] = "{source}";\n\n'
        "// the high byte of every value, then the low byte, as raw bytes\n"
        f"inline constexpr char HI[] =\n{hi};\n\n"
        f"inline constexpr char LO[] =\n{lo};\n\n"
        "// a truncated or mangled header fails here, at build time\n"
        "static_assert(sizeof(HI) == COUNT + 1 && sizeof(LO) == COUNT + 1,\n"
        '              "weights_data.hpp planes do not match COUNT");\n\n'
        "}  // namespace embedded\n")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--ckpt", default=str(ROOT / "runs/v1/latest.pt"))
    p.add_argument("--out", default="", help="also write the raw .bin blob here")
    p.add_argument("--header", default=str(ROOT / "mybot/weights_data.hpp"),
                   help="the compiled-in weights the bot actually uses")
    p.add_argument("--blocks", type=int, default=0,
                   help="ship only the first N residual blocks (0 = all)")
    args = p.parse_args()

    ck = torch.load(args.ckpt, map_location="cpu", weights_only=False)
    st = {k.replace("_orig_mod.", ""): v.float().numpy() for k, v in ck["net"].items()}
    cfg = ck["args"]
    width = cfg["width"]
    blocks = args.blocks or cfg["blocks"]

    tensors: list[np.ndarray] = []

    def conv(w):
        tensors.append(w.reshape(w.shape[0], -1).ravel())

    def vec(w):
        tensors.append(w.ravel())

    conv(st["stem.0.weight"])
    vec(st["stem.1.weight"]); vec(st["stem.1.bias"])
    for i in range(blocks):
        conv(st[f"blocks.{i}.c1.weight"])
        vec(st[f"blocks.{i}.n1.weight"]); vec(st[f"blocks.{i}.n1.bias"])
        conv(st[f"blocks.{i}.c2.weight"])
        vec(st[f"blocks.{i}.n2.weight"]); vec(st[f"blocks.{i}.n2.bias"])
    conv(st["flat.0.weight"])
    vec(st["flat.1.weight"]); vec(st["flat.1.bias"])
    for name in ("scalar.0", "scalar.2", "fuse.0", "fuse.2", "pi"):
        vec(np.ascontiguousarray(st[name + ".weight"].T)); vec(st[name + ".bias"])

    flat = np.concatenate(tensors)
    hidden = st["fuse.0.weight"].shape[0]
    head = st["flat.0.weight"].shape[0]
    u = bf16(flat)
    if args.out:
        header = struct.pack("<6i", MAGIC, width, blocks, hidden, head, flat.size)
        pathlib.Path(args.out).write_bytes(header + u.tobytes())
        print(f"wrote {args.out}")
    dest = pathlib.Path(args.header)
    write_header(dest, u, width, blocks, hidden, head,
                 f"{pathlib.Path(args.ckpt).name} iter {ck['iter']}")

    macs = (49 * 23 * width * 9 + blocks * 2 * 49 * width * width * 9
            + 49 * width * head + 14 * 128 + 128 * 128
            + (49 * head + 128) * hidden + hidden * hidden + hidden * 48)
    print(f"teacher iter {ck['iter']}: width {width}, blocks {blocks} "
          f"(checkpoint has {cfg['blocks']})")
    print(f"{flat.size:,} params, header {dest.stat().st_size/1e6:.2f} MB")
    print(f"{macs:,} MACs -> {macs*2.0/1e6:.0f}M points at 2/MAC, "
          f"{macs*3.0/1e6:.0f}M at 3/MAC")
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
