"""Exports an LSTM policy checkpoint (train/lstm_net.py) to lstmbot/weights.hpp.

Numerics, which lstmbot/lstmnet.hpp implements:
  * activations between layers are Q12 int16 (value * 4096, clamped to +-8);
  * every conv / linear weight row o is int16 at 12 bits, w_q = round(w / s_o)
    with s_o = max|w_o| / 2047, and the kernel's int32 accumulator is turned back
    into the real pre-activation as z = acc * s_o / 4096 + b_o, in float;
  * GroupNorm, SiLU, LayerNorm, the LSTM cell and the logits run in float from z.
So the only rounding is the 12-bit weights and the Q12 activations.

Blob (int16, high plane then low plane as export_cpp.py writes them), in order:
  conv    W [Cout][Cin*k*k]        stem, res15 (c1, c2)..., down, res8 (c1, c2)..., squeeze
  linear  W [K/2][Out][2]          embed, lstm0 [W_ih|W_hh], lstm1 [W_ih|W_hh], pi
Floats (FP[]), in the same order, per layer: scales [Out], bias [Out], and for
a normed conv gamma [Cout], beta [Cout]; then the previous-action table
[49][48] and the LayerNorm gamma [304], beta [304]. LSTM biases are b_ih + b_hh.

    python -m train.export_lstm --ckpt ../runs/ratchet_v8_sab/anchors/gen1.pt
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import time

import numpy as np
import torch

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from train.lstm_net import LSTMPolicy  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
ARCH_KEYS = ("c1", "b1", "c2", "b2", "squeeze", "embed", "hidden", "layers")
WMAX = 2047


def load(path: str) -> tuple[LSTMPolicy, dict]:
    ck = torch.load(path, map_location="cpu", weights_only=False)
    a = ck["args"]
    if a.get("arch") != "lstm":
        raise SystemExit(f"{path} is not an LSTM policy checkpoint")
    net = LSTMPolicy(**{k: a[k] for k in ARCH_KEYS})
    net.load_state_dict(ck["net"])
    return net.eval(), ck


def quant_rows(w: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    w = w.reshape(w.shape[0], -1).astype(np.float64)
    s = np.abs(w).max(axis=1) / WMAX
    s[s == 0] = 1e-12
    q = np.clip(np.round(w / s[:, None]), -WMAX, WMAX).astype(np.int16)
    return q, s.astype(np.float32)


def build(net: LSTMPolicy):
    """(int16 blob, float32 params), in lstmnet.hpp's reading order."""
    blob, fp = [], []

    def conv(m, norm=None):
        q, s = quant_rows(m.weight.detach().numpy())
        blob.append(q.reshape(-1))
        fp.extend([s, m.bias.detach().numpy().astype(np.float32)])
        if norm is not None:
            fp.extend([norm.weight.detach().numpy().astype(np.float32),
                       norm.bias.detach().numpy().astype(np.float32)])

    def linear(w, b):
        q, s = quant_rows(w)
        out_, k = q.shape
        blob.append(q.reshape(out_, k // 2, 2).transpose(1, 0, 2).reshape(-1))
        fp.extend([s, b.astype(np.float32)])

    conv(net.stem, net.stem_n)
    for blk in net.res15:
        conv(blk.c1, blk.n1)
        conv(blk.c2, blk.n2)
    conv(net.down, net.down_n)
    for blk in net.res8:
        conv(blk.c1, blk.n1)
        conv(blk.c2, blk.n2)
    conv(net.squeeze)
    linear(net.embed.weight.detach().numpy(), net.embed.bias.detach().numpy())
    for cell in net.lstm:
        w = torch.cat([cell.weight_ih, cell.weight_hh], dim=1).detach().numpy()
        linear(w, (cell.bias_ih + cell.bias_hh).detach().numpy())
    linear(net.pi.weight.detach().numpy(), net.pi.bias.detach().numpy())
    fp.append(net.prev_action.weight.detach().numpy().astype(np.float32).reshape(-1))
    fp.extend([net.in_norm.weight.detach().numpy().astype(np.float32),
               net.in_norm.bias.detach().numpy().astype(np.float32)])
    return np.concatenate(blob), np.concatenate([x.reshape(-1) for x in fp])


def write(dest: pathlib.Path, blob: np.ndarray, fp: np.ndarray, a: dict, source: str) -> None:
    u = blob.view(np.uint16)
    safe = [chr(c) if 32 <= c < 127 and chr(c) not in '"\\?' else "\\%03o" % c for c in range(256)]

    def literal(plane: np.ndarray) -> str:
        data = plane.astype(np.uint8).tobytes()
        return "\n".join('    "' + "".join(safe[c] for c in data[i:i + 2048]) + '"'
                         for i in range(0, len(data), 2048))

    floats = ",\n".join("    " + ", ".join(f"{x:.9e}f" for x in fp[i:i + 8]) for i in range(0, len(fp), 8))
    dest.write_text(
        "// GENERATED by bcsim/train/export_lstm.py. Do not edit.\n"
        f"// source: {source}\n// written: {time.strftime('%Y-%m-%d %H:%M:%S')}\n"
        "#pragma once\n#include <cstdint>\nnamespace wt {\n"
        f"constexpr int C1 = {a['c1']}, B1 = {a['b1']}, C2 = {a['c2']}, B2 = {a['b2']};\n"
        f"constexpr int SQ = {a['squeeze']}, EMB = {a['embed']}, HID = {a['hidden']}, LAYERS = {a['layers']};\n"
        f"constexpr std::uint32_t COUNT = {u.size}u;      // int16 weights\n"
        f"constexpr std::uint32_t N_FP = {fp.size}u;      // float parameters\n"
        f'constexpr char const SOURCE[] = "{source}";\n'
        f"inline constexpr char HI[] =\n{literal(u >> 8)};\n"
        f"inline constexpr char LO[] =\n{literal(u & 0xFF)};\n"
        f"inline constexpr float FP[] = {{\n{floats}\n}};\n"
        "static_assert(sizeof(HI) == COUNT + 1 && sizeof(LO) == COUNT + 1);\n"
        "static_assert(sizeof(FP) == N_FP * sizeof(float));\n"
        "}  // namespace wt\n")


def write_silu(dest: pathlib.Path, n: int = 16384, lo: float = -16.0) -> None:
    """lstmnet.hpp's SiLU table, so the bot does not compute 16k exps on turn 0."""
    x = lo + np.arange(n + 1, dtype=np.float64) * (-2 * lo / n)
    t = (x / (1.0 + np.exp(-x))).astype(np.float32)
    body = ",\n".join("    " + ", ".join(f"{v:.9e}f" for v in t[i:i + 8]) for i in range(0, len(t), 8))
    dest.write_text("// GENERATED by bcsim/train/export_lstm.py. Do not edit.\n"
                    f"// SiLU at {n + 1} points over [{lo}, {-lo}], for lstmnet.hpp.\n#pragma once\n"
                    f"namespace ln {{\ninline constexpr float SILU_T[{n + 1}] = {{\n{body}\n}};\n}}  // namespace ln\n")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--ckpt", required=True)
    p.add_argument("--out", default=str(ROOT / "lstmbot/weights.hpp"))
    a = p.parse_args()
    net, ck = load(a.ckpt)
    blob, fp = build(net)
    src = f"{pathlib.Path(a.ckpt).parent.name}/{pathlib.Path(a.ckpt).name} iter {ck.get('iter')}"
    write(pathlib.Path(a.out), blob, fp, ck["args"], src)
    write_silu(pathlib.Path(a.out).with_name("silu_table.hpp"))
    print(f"{blob.size:,} int16 weights + {fp.size:,} floats -> {a.out} ({src})")


if __name__ == "__main__":
    main()
