"""Writes weights.hpp for the LSTM probe bot: exact shapes, 16-bit values.

The values are random but realistic (Gaussian at each layer's init scale,
quantised per output row to the full int16 range), so the zip size measured
from this header is what a trained net of the same shape would ship at -- if
anything pessimistic, since trained weights are heavier-tailed and compress
better. Byte encoding is export_cpp.py's own: high plane then low plane,
printable bytes as themselves, the rest as 3-digit octal.

Blob order and layouts (the C++ in lstmnet.hpp reads it in exactly this order):
  conv    W [Cout][Cin*k*k]      (row-major, PyTorch's own flatten), b [Cout]
  linear  W [K/2][Out][2]        (pair-interleaved for the i16 dot kernel), b [Out]
  norm    gamma [C], beta [C]       (GroupNorm after stem/down/every block conv; LayerNorm before the LSTM)
  embed   [N_ACTIONS+1][48]
  lstm    [W_ih | W_hh] as linear, K = in + H, Out = 4H (gates i,f,g,o), b = b_ih + b_hh

    python gen_weights.py --c1 64 --c2 128 --hidden 128 > /dev/null
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import numpy as np
import torch

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "bcsim"))
from train.lstm_net import LSTMPolicy  # noqa: E402


def q_rows(w: np.ndarray) -> np.ndarray:
    """Per output row to the full int16 range."""
    w = w.reshape(w.shape[0], -1)
    s = np.abs(w).max(axis=1, keepdims=True) + 1e-12
    return np.round(w / s * 32767).astype(np.int16)


def q_vec(b: np.ndarray) -> np.ndarray:
    return np.round(b / (np.abs(b).max() + 1e-12) * 32767).astype(np.int16)


def interleave(wq: np.ndarray) -> np.ndarray:
    """[Out][K] -> [K/2][Out][2]."""
    out_, k = wq.shape
    assert k % 2 == 0, k
    return wq.reshape(out_, k // 2, 2).transpose(1, 0, 2).reshape(-1)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--c1", type=int, default=64)
    p.add_argument("--b1", type=int, default=1)
    p.add_argument("--c2", type=int, default=128)
    p.add_argument("--b2", type=int, default=2)
    p.add_argument("--squeeze", type=int, default=16)
    p.add_argument("--embed", type=int, default=256)
    p.add_argument("--hidden", type=int, default=128)
    p.add_argument("--layers", type=int, default=2)
    p.add_argument("--out", default=str(pathlib.Path(__file__).parent / "weights.hpp"))
    a = p.parse_args()

    torch.manual_seed(0)
    net = LSTMPolicy(c1=a.c1, b1=a.b1, c2=a.c2, b2=a.b2, squeeze=a.squeeze,
                     embed=a.embed, hidden=a.hidden, layers=a.layers)
    # Gaussian at the init's own scale: closer to trained weights than uniform
    with torch.no_grad():
        for prm in net.parameters():
            prm.normal_(0.0, (float(prm.std()) if prm.numel() > 1 else 0.0) + 1e-3)

    blob = []

    def conv(m):
        blob.append(q_rows(m.weight.detach().numpy()).reshape(-1))
        blob.append(q_vec(m.bias.detach().numpy()))

    def linear(w, b):
        blob.append(interleave(q_rows(w)))
        blob.append(q_vec(b))

    def norm(m):                      # GroupNorm / LayerNorm: gamma then beta
        blob.append(q_vec(m.weight.detach().numpy()))
        blob.append(q_vec(m.bias.detach().numpy()))

    conv(net.stem); norm(net.stem_n)
    for blk in net.res15:
        conv(blk.c1); norm(blk.n1); conv(blk.c2); norm(blk.n2)
    conv(net.down); norm(net.down_n)
    for blk in net.res8:
        conv(blk.c1); norm(blk.n1); conv(blk.c2); norm(blk.n2)
    conv(net.squeeze)
    linear(net.embed.weight.detach().numpy(), net.embed.bias.detach().numpy())
    blob.append(q_rows(net.prev_action.weight.detach().numpy()).reshape(-1))
    norm(net.in_norm)
    for cell in net.lstm:
        w = torch.cat([cell.weight_ih, cell.weight_hh], dim=1).detach().numpy()
        linear(w, (cell.bias_ih + cell.bias_hh).detach().numpy())
    linear(net.pi.weight.detach().numpy(), net.pi.bias.detach().numpy())

    u = np.concatenate(blob).view(np.uint16)
    # b_ih and b_hh are folded into one bias per LSTM layer on export
    n_torch = sum(prm.numel() for k, m in net.named_children() if k != "v" for prm in m.parameters())
    assert u.size == n_torch - a.layers * 4 * a.hidden, (u.size, n_torch)

    safe = [chr(c) if 32 <= c < 127 and chr(c) not in '"\\?' else "\\%03o" % c for c in range(256)]

    def literal(plane: np.ndarray) -> str:
        data = plane.astype(np.uint8).tobytes()
        return "\n".join('    "' + "".join(safe[c] for c in data[i:i + 2048]) + '"'
                         for i in range(0, len(data), 2048))

    pathlib.Path(a.out).write_text(
        "// GENERATED by lstmbot/gen_weights.py. Do not edit.\n#pragma once\n#include <cstdint>\n"
        "namespace wt {\n"
        f"constexpr int C1 = {a.c1}, B1 = {a.b1}, C2 = {a.c2}, B2 = {a.b2};\n"
        f"constexpr int SQ = {a.squeeze}, EMB = {a.embed}, HID = {a.hidden}, LAYERS = {a.layers};\n"
        f"constexpr std::uint32_t COUNT = {u.size}u;\n"
        f"inline constexpr char HI[] =\n{literal(u >> 8)};\n"
        f"inline constexpr char LO[] =\n{literal(u & 0xFF)};\n"
        "static_assert(sizeof(HI) == COUNT + 1 && sizeof(LO) == COUNT + 1);\n"
        "}  // namespace wt\n")
    print(f"{u.size:,} params -> {a.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
